### ISSUE TITLE
Error FindClusters() with large data set 

### ISSUE THREAD

**Issue by DNB86** [satijalab/seurat#166]
Hi, 
I am facing an issue using FindClusters() function, and this only with a large data set (140K cells). I don't have this issue with a smaller data sets. By the way, it looks like there is no "do.sparse = TRUE" option in Seurat v2 (I saw previous posts with the same problem).  I tried different resolution parameters (0.6, 0.8, 1.2 and 2). 
I can see the edge_XXXX.txt but not output_XXXX.txt
Thank you for help

Here the error: 
Exception in thread "main" java.lang.NumberFormatException: For input string: "1e+05"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at ModularityOptimizer.readInputFile(ModularityOptimizer.java:184)
        at ModularityOptimizer.main(ModularityOptimizer.java:74)
Error in file(file, "rt") : cannot open the connection
Calls: FindClusters -> RunModularityClustering -> read.table -> file

**Comment by andrewwbutler** [comment]
Try running  `options(scipen=10)` before running FindClusters(). The `do.sparse` parameter was removed in v2 because we now require these steps to use sparse matrices.

**Comment by DNB86** [comment]
Thanks a lot. That was the problem ... much more simple then I thought :)

**Comment by DNB86** [comment]
I have another question: is there a way to remove duplicates before running TSNE ? 
Thank you a lot for your help
