### ISSUE TITLE
Seurat V5 FastMNNIntegration and scVIIntegration errors

### ISSUE THREAD

**Issue by MWRR** [satijalab/seurat#7625]
I am working through the vignette [https://satijalab.org/seurat/articles/seurat5_integration.html], so I got errors when I was trying to run integration with FastMNNIntegration and scVIIntegration.
when running FastMNNIntegration
`obj <- IntegrateLayers(
  object = obj, method = FastMNNIntegration,
  new.reduction = "integrated.mnn",
  verbose = FALSE
)`
I got this error 

> Error in normarg_grid(grid, x) :
The current automatic grid maker returned an error when called
on 'x'. Please use setAutoGridMaker() to set a valid automatic
grid maker.

When running scVIIntegration
`obj <- IntegrateLayers(
  object = obj, method = scVIIntegration,
  new.reduction = "integrated.scvi",
  conda_env = "my conda environment 'scvi-env' location", verbose = FALSE
)`
I got this error

> Error in py_module_import(module, convert = convert) :
ModuleNotFoundError: No module named 'scanpy'
Run `reticulate::py_last_error()` for details.
> reticulate::py_last_error()

── Python Exception Message ────────────────────────────────────────────────────
Traceback (most recent call last):
  File "C:\Users\Rokaya\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'scanpy'

── R Traceback ─────────────────────────────────────────────────────────────────
    ▆
 1. └─Seurat::IntegrateLayers(...)
 2.   └─SeuratWrappers (local) method(...)
 3.     └─reticulate::import("scanpy", convert = FALSE)
 4.       └─reticulate:::py_module_import(module, convert = convert)
 
Scanpy has been installed by `conda install -c conda-forge scanpy`, but I got different error

> Error in py_module_import(module, convert = convert) :
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (C:\Users\Rokaya\.conda\envs\scvi-env\Lib\site-packages\torchmetrics\utilities\data.py)
Run `reticulate::py_last_error()` for details.

> reticulate::py_last_error()  ── Python Exception Message ──────────────────────────────────────────────────── Traceback (most recent call last):   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook     return _run_hook(name, _hook)            ^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook     module = hook()              ^^^^^^   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook     return _find_and_load(name, import_)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\h\.conda\envs\scvi-env\Lib\site-packages\scvi\__init__.py", line 7, in <module>     from ._settings import settings   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook     return _run_hook(name, _hook)            ^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook     module = hook()              ^^^^^^   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook     return _find_and_load(name, import_)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\h\.conda\envs\scvi-env\Lib\site-packages\scvi\_settings.py", line 5, in <module>     import pytorch_lightning as pl   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook     return _run_hook(name, _hook)            ^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook     module = hook()              ^^^^^^   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook     return _find_and_load(name, import_)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\h\.conda\envs\scvi-env\Lib\site-packages\pytorch_lightning\__init__.py", line 20, in <module>     from pytorch_lightning import metrics  # noqa: E402     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook     return _run_hook(name, _hook)            ^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook     module = hook()              ^^^^^^   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook     return _find_and_load(name, import_)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\h\.conda\envs\scvi-env\Lib\site-packages\pytorch_lightning\metrics\__init__.py", line 15, in <module>     from pytorch_lightning.metrics.classification import (  # noqa: F401   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook     return _run_hook(name, _hook)            ^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook     module = hook()              ^^^^^^   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook     return _find_and_load(name, import_)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\h\.conda\envs\scvi-env\Lib\site-packages\pytorch_lightning\metrics\classification\__init__.py", line 14, in <module>     from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook     return _run_hook(name, _hook)            ^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook     module = hook()              ^^^^^^   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook     return _find_and_load(name, import_)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\h\.conda\envs\scvi-env\Lib\site-packages\pytorch_lightning\metrics\classification\accuracy.py", line 18, in <module>     from pytorch_lightning.metrics.utils import deprecated_metrics   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook     return _run_hook(name, _hook)            ^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\h\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook     module = hook()              ^^^^^^   File "C:\Users\Rokaya\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook     return _find_and_load(name, import_)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\h\.conda\envs\scvi-env\Lib\site-packages\pytorch_lightning\metrics\utils.py", line 22, in <module>     from torchmetrics.utilities.data import get_num_classes as _get_num_classes ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (C:\Users\h\.conda\envs\scvi-env\Lib\site-packages\torchmetrics\utilities\data.py)  ── R Traceback ─────────────────────────────────────────────────────────────────     ▆  1. └─Seurat::IntegrateLayers(...)  2.   └─SeuratWrappers (local) method(...)  3.     └─reticulate::import("scvi", convert = FALSE)  4.       └─reticulate:::py_module_import(module, convert = convert)

--
scvi-tools has been installed using the [mambaforge](https://github.com/conda-forge/miniforge) distribution following the instructions on [https://docs.scvi-tools.org/en/stable/installation.html](url).
I tried solutions from the issue [https://github.com/satijalab/seurat/discussions/7156](url), however still the errors

> sessionInfo()

R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.utf8  LC_CTYPE=English_Australia.utf8   
[3] LC_MONETARY=English_Australia.utf8 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.utf8    

time zone: Australia/Sydney
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] reticulate_1.30          patchwork_1.1.2          ggplot2_3.4.2           
 [4] Azimuth_0.4.6.9004       shinyBS_0.61.1           SeuratWrappers_0.3.19   
 [7] pbmcsca.SeuratData_3.0.0 pbmcref.SeuratData_1.0.0 SeuratData_0.2.2.9001   
[10] Seurat_4.9.9.9058        SeuratObject_4.9.9.9091  sp_2.0-0                

loaded via a namespace (and not attached):
  [1] fs_1.6.3                          ProtGenerics_1.32.0              
  [3] matrixStats_1.0.0                 spatstat.sparse_3.0-2            
  [5] bitops_1.0-7                      DirichletMultinomial_1.42.0      
  [7] TFBSTools_1.38.0                  httr_1.4.6                       
  [9] RColorBrewer_1.1-3                tools_4.3.1                      
 [11] sctransform_0.3.5                 ResidualMatrix_1.10.0            
 [13] utf8_1.2.3                        R6_2.5.1                         
 [15] DT_0.28                           lazyeval_0.2.2                   
 [17] uwot_0.1.16                       rhdf5filters_1.12.1              
 [19] withr_2.5.0                       prettyunits_1.1.1                
 [21] gridExtra_2.3                     progressr_0.13.0                 
 [23] cli_3.6.1                         Biobase_2.60.0                   
 [25] spatstat.explore_3.2-1            fastDummies_1.7.3                
 [27] EnsDb.Hsapiens.v86_2.99.0         shinyjs_2.1.0                    
 [29] spatstat.data_3.0-1               readr_2.1.4                      
 [31] ggridges_0.5.4                    pbapply_1.7-2                    
 [33] Rsamtools_2.16.0                  R.utils_2.12.2                   
 [35] parallelly_1.36.0                 BSgenome_1.68.0                  
 [37] rstudioapi_0.15.0                 RSQLite_2.3.1                    
 [39] generics_0.1.3                    BiocIO_1.10.0                    
 [41] gtools_3.9.4                      ica_1.0-3                        
 [43] spatstat.random_3.1-5             googlesheets4_1.1.1              
 [45] dplyr_1.1.2                       GO.db_3.17.0                     
 [47] Matrix_1.5-4.1                    fansi_1.0.4                      
 [49] S4Vectors_0.38.1                  abind_1.4-5                      
 [51] R.methodsS3_1.8.2                 lifecycle_1.0.3                  
 [53] yaml_2.3.7                        SummarizedExperiment_1.30.2      
 [55] rhdf5_2.44.0                      BiocFileCache_2.8.0              
 [57] Rtsne_0.16                        grid_4.3.1                       
 [59] blob_1.2.4                        promises_1.2.0.1                 
 [61] shinydashboard_0.7.2              crayon_1.5.2                     
 [63] miniUI_0.1.1.1                    lattice_0.21-8                   
 [65] beachmat_2.16.0                   cowplot_1.1.1                    
 [67] annotate_1.78.0                   GenomicFeatures_1.52.1           
 [69] KEGGREST_1.40.0                   pillar_1.9.0                     
 [71] knitr_1.43                        GenomicRanges_1.52.0             
 [73] rjson_0.2.21                      future.apply_1.11.0              
 [75] codetools_0.2-19                  fastmatch_1.1-3                  
 [77] leiden_0.4.3                      glue_1.6.2                       
 [79] data.table_1.14.8                 remotes_2.4.2.1                  
 [81] vctrs_0.6.3                       png_0.1-8                        
 [83] spam_2.9-1                        cellranger_1.1.0                 
 [85] poweRlaw_0.70.6                   gtable_0.3.3                     
 [87] cachem_1.0.8                      xfun_0.39                        
 [89] Signac_1.10.0                     S4Arrays_1.0.5                   
 [91] mime_0.12                         pracma_2.4.2                     
 [93] survival_3.5-5                    gargle_1.5.2                     
 [95] SingleCellExperiment_1.22.0       RcppRoll_0.3.0                   
 [97] ellipsis_0.3.2                    fitdistrplus_1.1-11              
 [99] ROCR_1.0-11                       nlme_3.1-162                     
[101] bit64_4.0.5                       progress_1.2.2                   
[103] filelock_1.0.2                    RcppAnnoy_0.0.21                 
[105] rprojroot_2.0.3                   GenomeInfoDb_1.36.1              
[107] irlba_2.3.5.1                     KernSmooth_2.23-21               
[109] SeuratDisk_0.0.0.9020             colorspace_2.1-0                 
[111] seqLogo_1.66.0                    BiocGenerics_0.46.0              
[113] DBI_1.1.3                         tidyselect_1.2.0                 
[115] bit_4.0.5                         compiler_4.3.1                   
[117] curl_5.0.1                        BiocNeighbors_1.18.0             
[119] hdf5r_1.3.8                       xml2_1.3.5                       
[121] DelayedArray_0.26.6               plotly_4.10.2                    
[123] rtracklayer_1.60.0                scales_1.2.1                     
[125] caTools_1.18.2                    lmtest_0.9-40                    
[127] rappdirs_0.3.3                    stringr_1.5.0                    
[129] digest_0.6.33                     goftest_1.2-3                    
[131] presto_1.0.0                      spatstat.utils_3.0-3             
[133] rmarkdown_2.23                    XVector_0.40.0                   
[135] htmltools_0.5.5                   pkgconfig_2.0.3                  
[137] sparseMatrixStats_1.12.2          MatrixGenerics_1.12.2            
[139] dbplyr_2.3.3                      fastmap_1.1.1                    
[141] ensembldb_2.24.0                  rlang_1.1.1                      
[143] htmlwidgets_1.6.2                 DelayedMatrixStats_1.22.1        
[145] shiny_1.7.4.1                     zoo_1.8-12                       
[147] jsonlite_1.8.7                    BiocParallel_1.34.2              
[149] R.oo_1.25.0                       BiocSingular_1.16.0              
[151] RCurl_1.98-1.12                   magrittr_2.0.3                   
[153] scuttle_1.10.1                    GenomeInfoDbData_1.2.10          
[155] dotCall64_1.0-2                   Rhdf5lib_1.22.0                  
[157] munsell_0.5.0                     Rcpp_1.0.11                      
[159] stringi_1.7.12                    zlibbioc_1.46.0                  
[161] MASS_7.3-60                       plyr_1.8.8                       
[163] parallel_4.3.1                    listenv_0.9.0                    
[165] ggrepel_0.9.3                     CNEr_1.36.0                      
[167] deldir_1.0-9                      Biostrings_2.68.1                
[169] splines_4.3.1                     tensor_1.5                       
[171] hms_1.1.3                         BSgenome.Hsapiens.UCSC.hg38_1.4.5
[173] igraph_1.5.0.1                    spatstat.geom_3.2-4              
[175] RcppHNSW_0.4.1                    ScaledMatrix_1.8.1               
[177] reshape2_1.4.4                    biomaRt_2.56.1                   
[179] stats4_4.3.1                      TFMPvalue_0.0.9                  
[181] XML_3.99-0.14                     evaluate_0.21                    
[183] BiocManager_1.30.21.1             batchelor_1.16.0                 
[185] tzdb_0.4.0                        JASPAR2020_0.99.10               
[187] httpuv_1.6.11                     RANN_2.6.1                       
[189] tidyr_1.3.0                       purrr_1.0.1                      
[191] polyclip_1.10-4                   future_1.33.0                    
[193] scattermore_1.2                   rsvd_1.0.5                       
[195] xtable_1.8-4                      restfulr_0.0.15                  
[197] AnnotationFilter_1.24.0           RSpectra_0.16-1                  
[199] later_1.3.1                       googledrive_2.1.1                
[201] viridisLite_0.4.2                 tibble_3.2.1                     
[203] memoise_2.0.1                     AnnotationDbi_1.62.2             
[205] GenomicAlignments_1.36.0          IRanges_2.34.1                   
[207] cluster_2.1.4                     globals_0.16.2                   
[209] here_1.0.1

I appreciate any help

**Comment by Gesmira** [comment]
Hi, for the scVI error, it seems like your versioning is potentially off. Can you try creating a new conda environment and reinstalling? Furthermore, have you tried any of the suggestions [here](https://discourse.scverse.org/t/problems-importing-scvi-windows/914/6)?

**Comment by MWRR** [comment]
> Hi, for the scVI error, it seems like your versioning is potentially off. Can you try creating a new conda environment and reinstalling? Furthermore, have you tried any of the suggestions [here](https://discourse.scverse.org/t/problems-importing-scvi-windows/914/6)?

I created a new conda environment and reinstalled the package following [https://discourse.scverse.org/t/problems-importing-scvi-windows/914/15](url)
`conda create -n scvi-tools-env python=3.9 pip
pip install "jax[cpu]===0.3.14" -f https://whls.blob.core.windows.net/unstable/index.html --use-deprecated legacy-resolver
pip install scvi-tools`
still the same error.
When I tried to import scvi in Python this warning appeared 

> C:\Users\h\.conda\envs\scvi-env\lib\site-packages\scvi\_settings.py:63: UserWarning: Since v1.0.0, scvi-tools no longer uses a random seed by default. Run `scvi.settings.seed = 0` to reproduce results from previous versions.
  self.seed = seed
C:\Users\h\.conda\envs\scvi-env\lib\site-packages\scvi\_settings.py:70: UserWarning: Setting `dl_pin_memory_gpu_training` is deprecated in v1.0 and will be removed in v1.1. Please pass in `pin_memory` to the data loaders instead.
  self.dl_pin_memory_gpu_training = (

**Comment by Gesmira** [comment]
You mean you still get the `ModuleNotFoundError` for scanpy? Are you able to import scanpy in python? I don't think the scvi warning is necessarily worrisome, but you would probably be better off posting an issue in their repository if it is leading to the import errors.

**Comment by Gesmira** [comment]
Closing now due to lack of response. Please feel free to reopen if the error persists.

**Comment by cdxiaodong** [comment]
I got the issus  too

AppData\Roaming\Python\Python311\site-packages\scvi\_settings.py:70: UserWarning: Setting `dl_pin_memory_gpu_training` is deprecated in v1.0 and will be removed in v1.1. Please pass in `pin_memory` to the data loaders instead.
  self.dl_pin_memory_gpu_training = (
<frozen abc>:119: FutureWarning: SparseDataset is deprecated and will be removed in late 2024. It has been replaced by the public classes CSRDataset and CSCDataset.

For instance checks, use `isinstance(X, (anndata.experimental.CSRDataset, anndata.experimental.CSCDataset))` instead.

For creation, use `anndata.experimental.sparse_dataset(X)` instead.

![image](https://github.com/satijalab/seurat/assets/84082748/57f4bb3f-ba69-4af1-b060-870c42cc2ed7)
